# ansible-playbook -i inventory.ini config_single_docker_user.yml --extra-vars "username=myuser"
---
- name: Setup Docker for a single user
  hosts: all
  become: yes
  gather_facts: true

  tasks:
      - name: Run Docker setup tasks
        import_tasks: docker_setup_tasks.yml
