# ansible-playbook -i inventory.ini roles/user_setup/tasks/config_multi_docker_users.yml
---
- name: Setup Docker for multiple users
  hosts: all
  become: yes
  gather_facts: true

  tasks:
      - name: Get list of non-system users from the server
        shell: "getent passwd | awk -F: '($3>=1000) && ($3!=65534) {print $1}'"
        register: non_system_users

      - name: Convert user list to a variable
        set_fact:
            users: "{{ non_system_users.stdout_lines }}"

      - name: Run Docker setup tasks for each user
        include_tasks: docker_setup_tasks.yml
        loop: "{{ users }}"
        loop_control:
            loop_var: username
